### ISSUE TITLE
Autowire DefaultSender as SenderInterface

### ISSUE THREAD

**Issue by danaki** [yokai-php/messenger-bundle#28]
Getting `argument "$sender" of method "__construct()" references interface "Yokai\MessengerBundle\Sender\SenderInterface" but no such service exists. You should maybe alias this interface to the existing "yokai_messenger.sender" service.`

```
<?php

namespace App;

use Yokai\MessengerBundle\Sender\SenderInterface;

class MyClass
{
    /** @var SenderInterface */
    protected $sender;

    public function __construct(SenderInterface $sender)
    {
        $this->sender = $sender;
    }
}
```

**Comment by yann-eugone** [comment]
I will add this to the bundle code base in the next version.

For your information, you can do it by yourself in your `service.yaml` file : 

```yaml
services:
    Yokai\MessengerBundle\Sender\SenderInterface: '@yokai_messenger.sender'
```

This will create an alias of `yokai_messenger.sender` named `Yokai\MessengerBundle\Sender\SenderInterface` and the autowiring will work.

**Comment by danaki** [comment]
Yes, I've already added this line to my services.yaml
