### ISSUE TITLE
[add fixture] Swiftmailer : Recipient email on configuration

### ISSUE THREAD

**Issue by nicolas-joubert** [yokai-php/messenger-bundle#5]
Some email notifications doesnt need recipient and must be sent to a given address.
It would be great to be able to configure 'to' using parameters instead passing recipient.

**Comment by yann-eugone** [comment]
@nicolas-joubert this is already possible. when sending message through the `Swiftmailer` channel, the recipient could either a recipient or a static email. please see https://github.com/yokai-php/messenger-bundle/blob/master/Resources/docs/channels/swiftmailer.md#recipient
