### ISSUE TITLE
SwiftmailerChannel from_addr as array

### ISSUE THREAD

**Issue by nicolas-joubert** [yokai-php/messenger-bundle#7]
On SwiftMessage, from adresses can be string or array but configuration doesn't allow array on "from_addr".

Simple case is to allow ["contact@domain.com" => ''Your contact domain.com"]

@see Swift_Mime_SimpleMessage->setFrom($addresses, $name = null)

**Comment by yann-eugone** [comment]
@nicolas-joubert done in #9
